### ISSUE TITLE
Remove my character 

### ISSUE THREAD

**Issue by trilleplay** [dphuang2/PoGoBag#89]
Please remove my character from Pogobag.me
Username:trilleplay
google:trille849@gmail.com

**Comment by Yog** [comment]
could be usefull to have delete feature somewhere, since many people dont realize that you use pogoBag once and your nick stays there forever for Niantic to notice and just ban it. 
like this maybe:
![image](https://cloud.githubusercontent.com/assets/432220/18405667/4fa676ae-76f4-11e6-8885-8aa1ebc22ba9.png)

**Comment by Limeliz** [comment]
Or maybe an option to make yourself anonymous so the data is still stored for comparing but your trainer name is removed.
